package com.example.hhhapp.ui

import android.net.Uri
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.hhhapp.database.HireHerHandsDatabase
import com.example.hhhapp.database.WorkerProfile
import com.example.hhhapp.database.WorkerSkillCrossRef
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

class ApplyAsWorkerViewModel : ViewModel() {

    private val _message = MutableLiveData<String>()
    val message: LiveData<String> get() = _message

    // Store selected ID picture URI
    var idPictureUri: Uri? = null

    fun submitApplication(
        db: HireHerHandsDatabase,
        workerId: Int,
        bio: String,
        hourlyRate: Double,
        experience: Int,
        location: String,
        skillIds: List<Int>
    ) {
        val profile = WorkerProfile(
            workerID = workerId,
            workerBio = bio,
            averageRating = 0.0,
            hourlyRate = hourlyRate,
            location = location,
            experienceYears = experience,
            status = "Pending"
        )

        viewModelScope.launch(Dispatchers.IO) {
            // 1️⃣ Insert the worker profile
            val profileId = db.WorkerProfileDao().insertProfile(profile).toInt() // returns autogenerated ID

            // 2️⃣ Insert skills into WorkerSkillCrossRef
            skillIds.forEach { skillId ->
                val crossRef = WorkerSkillCrossRef(
                    profileId = profileId,
                    skillId = skillId
                )
                db.WorkerSkillCrossRefDao().insert(crossRef)
            }

            _message.postValue("Application submitted successfully!")
        }
    }
}
